name: destroy-staging

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '21'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_USER }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_KEY }}
          aws-region: ${{ secrets.TERRAFORM_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Define repository vars
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Destroy ECS infrastructure
        run: |
          cd terraform/modules/02-ecs
          terraform init
          terraform destroy -auto-approve \
          -var="project=$REPO_NAME" \
          -var="ecr_image=''"

      - name: Destroy ECR repository
        run: |
          cd terraform/modules/01-ecr
          terraform init
          terraform destroy -auto-approve \
          -var="project=$REPO_NAME"
