name: quality

on:
  workflow_call:
    pull_request:
      branches:
        - master

jobs:
  pipeline-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: run unit test
        run: mvn clean test

      #- name: run integration test
      #  run: mvn clean integration-test